version: 2.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
build:
  project: sources/EncodingChecker.sln
  verbosity: minimal
  
before_build:
  - nuget restore sources/EncodingChecker.sln

after_build:
  - 7z a EncodingChecker.zip %APPVEYOR_BUILD_FOLDER%/sources/EncodingChecker/bin/Release/*

artifacts:
  - path: EncodingChecker.zip
    name: EncodingChecker